[package]
name = "thevenin-control"
version = "0.1.0"
edition = "2024"
description = ".control block interpreter for thevenin circuit simulator"
license = "BSD-3-Clause"
repository = "https://github.com/cramt/thevenin"

[dependencies]
thevenin-types = { path = "../thevenin-types", version = "0.3.0" }
thevenin = { path = "../thevenin", version = "0.3.0" }
cirq-ir = { path = "../cirq-ir", version = "0.1.0" }
cirq-frontend = { path = "../cirq-frontend", version = "0.1.0" }
thiserror.workspace = true

[dev-dependencies]
cirq-spice-import = { path = "../cirq-spice-import", version = "0.1.0" }
